os:
- linux
language: python
python:
- '3.6'
env:
  global:
  - TE_SEQUENCE_FASTA=~/ref.fa
  - CONDA_PREFIX=~/conda
  - secure: dfbb83QcBKliQ8H6eMU9WTHYrEvLVRqkGv1Wt+tKs4NgVGz80FFXNvYlWDbA+YBtlQ6q4TB+/dL4uApw2aJorI6RULNpx+uB9FjT57oSMtDnf2yH5sFGa8K6PYwFSC5gkY0IXZ1kY1fkol+ivvrp6l0i9b4z2IVomBxmrBMx7tYO68OHgwIv6FjxP+f0K99gmsoGZLYiCNuW9fB3gWFnNLGVGxbg7gjL0kFR7h3ELkaPuzuMZJ90ixSGcQGEtBOdOHF8bVUuE6voXco4dVAgKfOgAnXVZZO+nJdPMo0BzPO+clmnrTWvFJpmQg1D8nBluCdK3806ePyL2NJZv8Yc43qipf7tJ8KK4/KX0UGNEk04mrr3fto1eb6GMdBxOy1Z5SWLS+A1JeP4oQLRpxeBUjZKckfOnMQ7GA4F226icSMew2AniojSrAG/eihczlynCCyARSACxpxnK+6QZO6FqNZ2iTsinBm8waD+DN1lYaCBEhbjJgSjEHbGxbmi8C3r1N41jtxrF1H4fNWPtMdMQvBP0HnhrS2am2TyaxnXyS+YDyW68/Bs3AvnV9cqSAI2u/kZ7kgX+ieCs1hlupX5UAmlNwFWisK7tBAJClyFb2tBjol59WqFZuPai22/iPS9JwMZqO4MjiGu6HuX5+msa9C1emEymnhnQGak9qGED/g=
  - secure: UIBpSW2z8KgjEPUAh/I041aZs2cidtUm99U0/Og2FKNvmR6fCyXex4eg9Tk3C8dLjqVAlUoFswD/GrQf+ng/+8ek39ET47XjIDs9LSdbsFwy5Uez+uQlSeFxAxzUucOE0Kno54sCsafcxo8AUZieHaJF8zy80fR44EKqZl2XuOx6hZJGmDq/MSTNTfoYP29lIP/Y5K8s3i9acj79iXyDu7ysS/uesqwf7yLTt3xaF6K5HSW3EO+DVFhz4pmd2Hn/3tS8hSLV33M61LF9Bgi58LUTZ9Be3Jvf+8M1KfrpPA+YogpdqiZR62TqFyGkC8u3/Ra787b0xzgFJK3b9prE1QZtQr4kkS489uQHGWOAEnDfS+7Z4Y9aj/wUQac1ecErI5IOP/QhFOIF6LqI+2qi+3kLDookXTPSs4hHtpbMA5qqej7w4Vu++2Wz/2XTLg17FbgnQ9EDwiomcYj0XDTWbsGimfNM3PFsfqEitnTvgCM2US8bTfrJowp8kumdjG28PbnsHznaXGRJmm98YftCY0SuYOxcn80IcDQWiHPkKaJ4oN1zrPLrvSHZWNeDc1fKm5j7hM1FnPZ2N1AzXlzj2DN/oEVfLij9xycCQqUsmdjDs59MPimkZ00D1VhFusnfUAKMCUsy5YIdLoudwRqJFbGSkB70/P2ERehcYfg5J38=
  - secure: go/4X6KeeYcyAycKRixUHeSXVI1K/P7OtY9wW1fdoM1XtXTeA318+7odHxusMJk6TUDOeWcHlrow2EBEtaLDxKyR2WErKNyvZc7dnLJtPliE28I74fDeDzr+3g8BlFmS8ub6f5xj7lmaDsoymbYcB4XzIAMg1tqMU0vRg0Zx+iR1JhikiBSw4B/ef8pCMMtzfFjv5amVfd8e48355q+sd/jvCw6/b+O9z+iRvPuOTuJNtgg9jaQzcVsGvafFlADItkNdemH62WCRY1vg5XDphr72HBP3700sfpqb5TYX/a+x18ncZcVQaGpS9rp+naIKL9e8XdhMbOffwLsWNruTb/kfipQIBRriD+1cGDpGQgpnF4El8pwr74mmIK5Faa0dk8vdCikkG7gX2KbItGCHYoLhpX8VEMNv+8pW2K9KPdjM1ZqlAqyNOgiq7KcXnCdnnxeTc4ghaiqd/2HrdMiEGj9/5oZ5TZgIuhPpjaLyZBG43boQ3J0otk11ej7MlKx5lTgtfIKCtTJ++QA628sq8S3q0WOaIfBEnnil85q0z3e3DFWajmamBsA5RM53GazIacU4jZxYIt9y+bgOrKonupMr8yc2ua8Y5ycaKDJOJ+N+0XwjaXOsi0m0qApUYsY71xCMnQiH5b8TqGncolnDlf7sb1eo/RGt76WSEx1gzBw=
install:
- git fetch --unshallow
- python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -bp $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda --version
- conda config --add channels mvdbeek
- conda config --add channels bioconda
- conda config --add channels conda-forge
- conda install tox coveralls bwa cap3 samtools virtualenv conda-build -c conda-forge -c bioconda
- samtools --version
- pip install tox-travis
- virtualenv /home/travis/.planemo/gx_venv
- conda build --python "$TRAVIS_PYTHON_VERSION" conda/multiprocessing-logging
- conda build --python "$TRAVIS_PYTHON_VERSION" conda/readtagger
- curl -L https://github.com/bardin-lab/dmel-transposon-reference-data/raw/master/fasta_sequences/dm6_TE_annotations_sequences.fasta -o ~/ref.fa
script: tox
after_success:
- coveralls
deploy:
- provider: pypi
  user: mvdbeek
  password:
    secure: t3Icum4IahHP8eF+e8OEy2d0/Vb+AUd8GWuYM/SoG/Fqf2OBKiyS2fJGfL5N96k4JGzxfIMoV5vNJ/WPiNA3wPluYb8KW6ork2Mp/0UuxHTCkkdmjeGE528qWkprS8F+0N4qDDdK+6k+hOmGdSiiRryCzIz2deAb07npNytnlqbe70CGskTwrBAdxjFmkvjxMje0QSxdFIBNksBt4qd3x1UjMJ14BtYFPSgAXE0HYwEzrFyMLIXoA3kevCKpXYsX8bT7uPpNNKDvyG6hTyKraUPAXv/eX3JfFFu9vURzJQik5UQ+0S1Wc1hyevc9nZkTyIEpPOqmoZvBU0lI/wNGlw0c72VDwLxvJyspq/5HTsQaHih4KJX7jFHjVRbIT/Fu8KKp7gQyAAtEwgj+6SeE++EFDGSlrjqST3lHWjAZE07ODuCH/DS4oSFajrnqu7a481D03cm14FFGr6M6joxbPpylOPSqjJkVvndt06+68zdXtKg8UOHLNmUyLudZez5oEr277MQYtAZkDEVXn8mpysxeh7DdlenLQdQaW3rA65GuIe5F4nGRYX5xYwedXCQEZNWv1LqjMb1zDvlkRQ3l8e1fn8Swrdj+/Z2mZB4kq3tSS3mHL3H9euFHRbzRuE/fRLu1rkyTJH5K99Y5HrjT8C1n75md/BS3lSVggB7zcyc=
  skip_existing: true
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: bash conda/deploy.sh
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: bash galaxy/deploy.sh
  on:
    tags: true
